[server]
headless = true
port = $PORT
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
caching = true
showErrorDetails = true

[logger]
level = "info"

[runner]
magicEnabled = true
installTracer = false
fastReruns = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 